### ISSUE TITLE
Message closing window after edit & save register content

### ISSUE THREAD

**Issue by Lukas3** [tomtom/tregisters_vim#1]
SO: Win 7-64; Gvim 8-32 bits; tlib installed+updated
After edit and save register and close window -> message:
Error in function <SNR>164EditCallback[15]... <SNR>162EditCallback:
line 5
E121 variable: tlib_world
line 10
E119 function tlib#input#Resume

Best regards

**Comment by tomtom** [comment]
Hi!

 > After edit and save register and close window -> message:
 > Error in function 164EditCallback[15]... 162EditCallback:
 > line 5
 > E121 variable: tlib_world

Thanks you very much for the report. It seems the edit list 
functionality is currently broken. I cannot tell when I have time to fix it.

Regards
